name: Test deployment

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.32.3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17.x
          cache: "pnpm"

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmmirror.com
          pnpm install --frozen-lockfile

      - name: Build website
        run: pnpm run build
