name: Test deployment

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Clone the data repo
        run: |
          git clone https://jihulab.com/zhoushengdao.github.io/blog.git
          git clone https://jihulab.com/zhoushengdao.github.io/docs.git

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "pnpm"

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmmirror.com
          pnpm install --no-frozen-lockfile

      - name: Build website
        run: pnpm run build

      - name: Commit pnpm-lock.yaml
        run: |
          git status
          git config --global user.email "zhoushengdao@sina.cn"
          git config --global user.name "周盛道"
          git add pnpm-lock.yaml
          git commit -m "update pnpm-lock.yaml"
          git push --force origin HEAD:$GITHUB_REF

      - name: Archive artifact
        shell: sh
        run: |
          for f in $(chmod -c -R +r . | awk '{print substr($3, 2, length($3)-2)}')
          do
            echo "::warning::Added read permission to $f"
          done
          tar \
            --dereference --hard-dereference \
            --directory "./build" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ${{ runner.temp }}/artifact.tar
